spring:
  datasource:
    password: 123456
    url: jdbc:postgresql://localhost:5432/registration
    username: postgres
  jpa:
    hibernate:
      ddl-auto:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  mail:
    host: smtp.web.de
    port: 587
    username: gatekeeper.cardhaven@web.de
    password: MagicGateKepper22
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
