#docker-compose is to make image and container for the file

version: "3.8"
services:
  api:
# . because the docker-compose is in the same directory with the dockerfile
    build: .
    container_name: api_c
    ports:
      - '8080:8080'
    volumes:
      - ./src/api/axios:/app
      - ./axios/node_modules:/app

  templates:
    build: .
    container_name: templates_c #c for container
    ports:
      - '3000:3000'
#the both next properties start the container in interactive mode (don't automatically shout down)
    stdin_open: true
    tty: true